simp/pupmod-simp-ssh

- .fixtures.yml
- .fixtures.yml.local
- .travis.yml
- Gemfile
- manifests/server/conf.pp
- spec/fixtures/modules/augeasproviders
- spec/fixtures/modules/augeasproviders_grub
- spec/spec_helper.rb
SIMP-169 #close Update ssh for travis
> (SIMP-169) Update pupmod-simp-ssh for travis

- manifests/server/conf.pp
- spec/classes/init_spec.rb
- spec/classes/server/conf_spec.rb
- spec/classes/server_spec.rb
Fixed some necessary includes.
Updated spec tests.
> (SIMP-58) Final testing and bug fixes.

- manifests/server.pp
Disable openssh-ldap if not using global ldap
> (SIMP-512) Disable openssh-ldap

- build/pupmod-ssh.spec
- manifests/server/conf.pp
Do not permit empty ssh passwords.
SIMP-542 #close
> (SIMP-542) CCE-3660-8 SSH password compliance

- .fixtures.yml
- build/pupmod-ssh.spec
- manifests/client.pp
- manifests/init.pp
- manifests/server.pp
- manifests/server/conf.pp
- metadata.json
Enables compliance checking support for ssh module
SIMP-720 #comment added compliance support
> (SIMP-720) Map 800-53 requirements to hiera

- build/pupmod-ssh.spec
- manifests/client.pp
- manifests/server/conf.pp
- metadata.json
SIMP-1177 #comment update
SIMP-1186 #comment ssh done
> (SIMP-1186) Use_haveged is a global catalyst

- CHANGELOG
- manifests/server/conf.pp
- metadata.json
Modified AuthorizedKeysCommand to be /usr/bin/sss_ssh_authorizedkeys
when sssd is enabled.
SIMP-1443 #close
> (SIMP-1443) Updated AuthorizedKeysCommand logic

- metadata.json
Removed duplicate and conflicting declaration of `simp/simplib`
SIMP-1591 #comment Additional fix for `metadata.json`
> (SIMP-1591) Fix `metadata.json` more betterer

- CHANGELOG
- build/rpm_metadata/requires
- metadata.json
> (SIMP-2024) Update iptables dep version

- .fixtures.yml
- CHANGELOG
- build/rpm_metadata/requires
- manifests/client.pp
- manifests/client/host_config_entry.pp
- manifests/client/params.pp
- manifests/server/conf.pp
- manifests/server/params.pp
- metadata.json
- spec/classes/client_spec.rb
- spec/classes/server/conf_spec.rb
- spec/defines/client/host_config_entry_spec.rb
- templates/ssh_config.erb
* Updated the default ciphers to CTR
* Modified to work with the latest iptables
* Fixed a couple of data types
SIMP-2468 #close
> (SIMP-2468) Update default ciphers to CTR

- .travis.yml
- manifests/server.pp
- spec/classes/server_spec.rb
- file was subscribing to a resource that didn't exist any more
SIMP-2122 #comment further fixes to get system to run cleanly
> (SIMP-2122) Fixed dependency in ssh module

- .gitlab-ci.yml
- CHANGELOG
- manifests/client/host_config_entry.pp
- metadata.json
> (SIMP-2822) remove non-ascii characters from host_config_entry.pp

- CHANGELOG
- lib/puppet/parser/functions/ssh_autokey.rb
- lib/puppet/parser/functions/ssh_global_known_hosts.rb
> (SIMP-2879) Move simp_autofiles to Puppet vardir

- lib/puppet/parser/functions/ssh_autokey.rb
- lib/puppet/parser/functions/ssh_global_known_hosts.rb
Still need to make sure we account for different environments with
server side stored artifacts.
SIMP-2879 #close
> (SIMP-2879) Need to handle different environments

- .gitlab-ci.yml
> (SIMP-3234) add gitlabci to simp module

- .fixtures.yml
- .gitlab-ci.yml
- .travis.yml
- CHANGELOG
- Gemfile
- metadata.json
SIMP-3903 #comment ssh update to concat 4.x
> (SIMP-3903) ssh update to concat 4.x

- .gitlab-ci.yml
- .travis.yml
- CHANGELOG
- Gemfile
- manifests/server/params.pp
- metadata.json
- spec/acceptance/nodesets/oel.yml
- spec/classes/server/conf_spec.rb
- spec/defines/client/host_config_entry_spec.rb
Added support for Puppet 5 and Oracle Linux
> (SIMP-4009) Add Puppet 5 and OEL Support

- .gitlab-ci.yml
- .puppet-lint.rc
- .travis.yml
- CHANGELOG
- Gemfile
- manifests/client.pp
- manifests/server.pp
- metadata.json
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/oel.yml
- spec/classes/client_spec.rb
- spec/classes/server_spec.rb
> (SIMP-2971) Add $simp_options::package_ensure

- .gitlab-ci.yml
- .travis.yml
- Gemfile
SIMP-5585 #comment Added pup5 test assets to ssh
> (SIMP-5585) Test assets support Puppet 5

- .fixtures.yml
- .gitlab-ci.yml
- CHANGELOG
- README.md
- REFERENCE.md
- manifests/authorized_keys.pp
- manifests/server.pp
- manifests/server/conf.pp
- metadata.json
- spec/acceptance/suites/default/00_default_spec.rb
- spec/acceptance/suites/default/10_pam_oath_spec.rb
- spec/classes/server/conf_spec.rb
- spec/classes/server_spec.rb
- spec/defines/client/host_config_entry_spec.rb
- spec/fixtures/hieradata/authorizedkeyscommand.yaml
- spec/fixtures/hieradata/authorizedkeyscommand_with_empty_user.yaml
- spec/fixtures/hieradata/custom_entries.yaml
- spec/fixtures/hieradata/rhostsrsaauthentication_disabled.yaml
- spec/spec_helper.rb
* Allow users to specify arbitrary sshd configuration settings via Hiera
* Coverted the module to use Hiera v5 tests
SIMP-6305 #close
> (SIMP-6305) Add ability to set abitrary sshd conf

- .travis.yml
- CHANGELOG
- lib/puppet/functions/ssh/autokey.rb
- lib/puppet/parser/functions/ssh_autokey.rb
- metadata.json
Switched 'system' to Puppet::Execution.execute
SIMP-6624 #close
> (SIMP-6624) Fix memory issue in functions problem

- .gitlab-ci.yml
- CHANGELOG
- Gemfile
- metadata.json
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/oel.yml
SIMP-7317 #close
SIMP-7202 #comment Add EL8 support to simp-ssh
> (SIMP-7317) Add EL8 support

- CHANGELOG
- manifests/server/conf.pp
- spec/classes/server/conf_spec.rb
- spec/spec_helper.rb
* Remove UsePrivilegeSeparation from systems that do not support it and
add it otherwise
SIMP--7539 #close
> (SIMP-7539) Handle UsePrivilegeSeparation warning
