simp/pupmod-simp-ssh

manifests/server/params.pp

Fallback params need to be set when FIPS is not enabled.
SIMP-336 #close Update ssh server params

(SIMP-336) Update ssh server params

---

manifests/server/conf.pp
manifests/server/params.pp

Added explicit cases for FIPS and non-FIPS mode as well as reasonable
default cases for RHEL7 and below.
Also added support for the KexAlgorithms to get those reasonably in line
with the FIPS requirements out of the box.
SIMP-291 #close #comment Modern Updates

(SIMP-291) Modernize the Ciphers, MACs, and Kex

---

CHANGELOG
metadata.json

`simp/common` and `simp/concat` are listed as dependencies in
`metadata.json`, which breaks resolution when installing from the Forge.
This patch fixes the issue by keeping references to `simp/simplib` and
`simp/simpcat`.
SIMP-1591 #close

(SIMP-1591) Fix old dependencies

---

manifests/client/params.pp
manifests/server/params.pp
spec/classes/server/conf_spec.rb
spec/defines/client/host_config_entry_spec.rb

This patch corrects the `Ciphers` setting in `ssh_config` and
`sshd_config`, restricting the ciphers selcted to those approved under
the FIPS 140-2 certifications for Red Hat Enterprise Linux OpenSSH.
Prior to this, the cipher-suite erroniously included the unapproved
GCM-mode ciphers.
SIMP-2665 #close

(SIMP-2665) Correct OpenSSH FIPS cipher-suite

---

CHANGELOG
manifests/server/conf.pp

- Changed the default value of simp_options::trusted_nets to ['ALL'] to prevent
permanent lockouts when a console isn't available.
SIMP-2735 #close

(SIMP-2735) Set trusted_nets to ALL by default

---

CHANGELOG
manifests/server/conf.pp
metadata.json

The trusted_nets option has been reverted to 'ALL' since the more
common use case is to install on a virtual machine in one of the
popular cloud infrastructures.
If you do this, then the default of 'simp_options::trusted_nets' is
wrong 100% of the time.
SIMP-2897 #comment Reverted trusted_nets setting
SIMP-2904 #close

(SIMP-2897) Revert ssh::server::conf::trusted_nets

---

CHANGELOG
manifests/server.pp

https://simp-project.atlassian.net/browse/SIMP-2940
The module change the following permissions from the RPM default, which triggers on some security scans. Since security is not enhanced by the changes, it is recommended to leave them at RPM default.
*Set /etc/ssh/moduli permissions to ‘0644’ instead of ‘0600’*
https://bugzilla.redhat.com/show_bug.cgi?id=1043661
*Set /var/empty/sshd to '0711' instead of '0744'*
This actually makes more sense since you'd need to traverse the directory to read the files within.

(SIMP-2940) Unnecessary permission changes

---

CHANGELOG
build/rpm_metadata/requires
metadata.json

concat 3.0.0 is fully backward compatible with 2.x.

(SIMP-3613) ssh: Update to concat 3.0.0

---

.fixtures.yml

Pin concat to 3.0.0 in .fixtures.yml, as metadata.json bounds
concat to < 4.0.0.

(SIMP-3613) ssh: Pin concat to 3.0.0 in .fixtures.yml

---

CHANGELOG
manifests/server/conf.pp
manifests/server/params.pp
metadata.json
spec/classes/server/conf_spec.rb
spec/fixtures/hieradata/rhostsrsaauthentication_disabled.yaml

By default, do not configure RhostsRSAAuthentication in sshd_config for
versions of openssh that no longer allow that option (openssh 7.4 and
greater).  The user can still configure this option to match the
outdated STIG checks, but, sshd will emit an error message when
it parses its configuraton file.
SIMP-5718 # close

(SIMP-5718) sshd RhostsRSAAuthentication error

---

.gitlab-ci.yml
CHANGELOG
manifests/server/conf.pp
metadata.json

- Updated $app_pki_external_source to accept any string. This matches the
functionality of pki::copy.
SIMP-5296 #comment Updated ssh
SIMP-5307 #close

(SIMP-5307) updated $app_pki_external_source type

---

CHANGELOG
spec/acceptance/nodesets/default.yml
spec/acceptance/nodesets/oel.yml
spec/acceptance/suites/default/00_default_spec.rb

Altered 00_default_spec.rb to stop deleting all ssh keys in test
Replaced puppet_environment with puppet_collection in nodesets
SIMP-5429 #close

(SIMP-5429) Delete fewer keys in default acceptance test

---

CHANGELOG
manifests/server/conf.pp

- Add a space when joining back together the elements of command.
SIMP-5825 #close

(SIMP-5825) SSH subsystem error

---

CHANGELOG
manifests/server/conf.pp
metadata.json

- Use Puppet String in lieu of simplib's deprecated Puppet 3 to_string
- Use simplib::nets2ddq in lieu of deprecated Puppet 3 nets2ddq
SIMP-6121 #close

(SIMP-6121) Convert to_string() calls

---

CHANGELOG
Gemfile
REFERENCE.md
manifests/server/conf.pp
spec/acceptance/suites/compliance/00_default_spec.rb
spec/acceptance/suites/default/05_non_standard_ports_spec.rb
spec/acceptance/suites/default/10_pam_oath_spec.rb
spec/classes/server/conf_spec.rb
types/authentications.pp
types/loglevel.pp
types/permitrootlogin.pp
types/syslogfacility.pp

- Add multiple port support
- The ssh::server::conf::port entry can now take an Array of ports
- `selinux_port` resources are created for each non-standard entry
- Update the required version of simp-beaker-helpers to work around Highline
issues in the compliance acceptance tests.
SIMP-6890 #close

(SIMP-6890) Add multi-port support

---

README.md
REFERENCE.md
manifests/server/conf.pp

Parameter passwordauthenication is no longer optional, update
documentation to reflect
SIMP-6844 #close

 (SIMP-6844) Correct simp-ssh documentation 

---

CHANGELOG
manifests/server/conf.pp
metadata.json

Multiple ports with SELinux caused a duplicate resource declaration
of policycoreutils-python, which was already required by vox-selinux

(SIMP-MAINT) Fixed issue with duplicate packages

---

.gitlab-ci.yml
CHANGELOG
REFERENCE.md
functions/add_sshd_config.pp
functions/parse_ssh_pubkey.pp
manifests/server/conf.pp
metadata.json
spec/classes/server/conf_spec.rb
spec/fixtures/hieradata/remove_entries.yaml
spec/fixtures/hieradata/remove_subsystems.yaml
spec/functions/ssh/add_sshd_config_spec.rb

- Added two `ssh::server::conf` parameters to allow users to ensure
specific sshd configuration is removed from sshd_config:
- `ssh::server::conf::remove_entries`
- `ssh::server::conf::remove_subsystems`
- Allow use of simp-simplib 4.X.
- Break out compliance tests into the compliance stage in GitLab

(SIMP-7006) ssh::server::conf allow removal of entries

---

.fixtures.yml
CHANGELOG
manifests/server/conf.pp
metadata.json
spec/classes/server/conf_spec.rb

- Remove dependency on the simp/sssd module
- Ensure that the sssd-common package is installed if required and allow the
user to disable this if necessary
SIMP-7596 #close

(SIMP-7596) Break simp/sssd dependency

---

.gitlab-ci.yml
.travis.yml
Gemfile

This patch updates the puppet and ruby versions in the Gitlab CI
pipeline to reflect the latest PE LTS releases.  Most notably, it adds
specific tests for PE2019.8 LTS.
SIMP-7934 #close
[SIMP-7848] #comment Add PE2019.8 to GL CI in pupmod-simp-ssh
[SIMP-7855] #comment Update GL CI to PE2018.1.15 in pupmod-simp-ssh
[SIMP-7848]: https://simp-project.atlassian.net/browse/SIMP-7848
[SIMP-7855]: https://simp-project.atlassian.net/browse/SIMP-7855

(SIMP-7848) Add PE2019.8 to pupmod-simp-ssh GL pipeline

---

CHANGELOG
REFERENCE.md
manifests/authorized_keys.pp
manifests/client/host_config_entry.pp
manifests/client/params.pp
manifests/init.pp
manifests/server/params.pp
metadata.json
spec/defines/client/host_config_entry_spec.rb

Fixed:
- No longer set HostKeyAlgorithms on the client configuration by default
[SIMP-8811] #close
[SIMP-8811]: https://simp-project.atlassian.net/browse/SIMP-8811

(SIMP-8811) Do not set client HostKeyAlgorithms

---

.github/workflows/pr_glci.yml
.github/workflows/pr_glci_manual.yml
.github/workflows/pr_tests.yml
.gitlab-ci.yml

This patch updates the standardized GitHub Actions that trigger GLCI
pipelines:
- Still preemptively cancels existing GLCI pipelines for the same
branch, EXCEPT when a pipeline is for the same commit hashref.
- Refactored common GLCI logic into new composite run steps actions:
- [github-action-gitlab-ci-pipeline-trigger@v1][0]
- [github-action-gitlab-ci-syntax-check@v1][1]
This patch also enforces the standardized asset baseline using
simp/puppetsync, and may apply other updates to ensure conformity.
CI: SKIP MATRIX
[SIMP-9347] #close
[SIMP-9266] #comment Standardized GHA + assets in pupmod-simp-ssh
[SIMP-9279] #comment `.fixtures.yml` triggers GLCI acc for pupmod-simp-ssh
[0]: https://github.com/simp/github-action-gitlab-ci-pipeline-trigger
[1]: …

(SIMP-9266) Improve GHA GCLI trigger in pupmod-simp-ssh

---

spec/acceptance/nodesets/default.yml
spec/acceptance/nodesets/oel.yml

Reinstate roles in nodesets so `host_as('server')` and `host_as('client')` return
appropriate nodes and the tests run.
SIMP-9393 #close

(SIMP-9393) ssh: default suite execute 0 examples

---

CHANGELOG
manifests/client/host_config_entry.pp
spec/acceptance/suites/default/00_default_spec.rb
spec/acceptance/suites/default/05_non_standard_ports_spec.rb
spec/acceptance/suites/default/10_pam_oath_spec.rb
spec/acceptance/suites/default/files/ssh_test_script_change_pass
spec/defines/client/host_config_entry_spec.rb

- openssh v8.0  dropped support for SSH protocol 1.  This
fix checks the version of openssh installed and removes deprecated
values.
- Changes had to be made to the tests for the following:
- Test for changes to crypto are failing on EL8 because of global crypto
policy.  This test is temporarily bypassed until it is fixed in
SIMP-9412
- OEL tests are failing because packages are not being installed.
An update was put in simp-beaker-helpers to the enable_epel method
to enable the repo on OEL systems.
- Alternate port tests are failing because selinux_port is not set up
correctly.  SIMP-9425 was created to address this.  The vox_selinux
module was included as a work around until this is fixed.
- simp_options::firewall was set to true in the alternate port test
because OEL has the firewall …

(SIMP-8932) Update ssh_config host entries

---

CHANGELOG
Gemfile
manifests/server/conf.pp
spec/acceptance/nodesets/default.yml
spec/acceptance/nodesets/oel.yml
spec/acceptance/suites/default/05_non_standard_ports_spec.rb
spec/classes/server/conf_spec.rb

- Running selinux_port was failing when the voxpupuli selinux
modules was not included. selinux_port requires the packages
installed by the module.  Verified that including the module
would not do anything by default except install the packages.
- Added memory to the EL8 test nodes.  Tests were consistently getting an
out of memory error when selinux_port was called.  semanage,
used by the selinux_port resource, allocates a lot of memory
when loading the selinux policies it needs.
[SIMP-9412] #close
[SIMP-9412]: https://simp-project.atlassian.net/browse/SIMP-9412

(SIMP-9412) SSH selinux_port errors

---

CHANGELOG
REFERENCE.md
functions/add_sshd_config.pp
manifests/server/conf.pp
manifests/server/params.pp
spec/classes/server/conf_spec.rb
spec/fixtures/hieradata/enable_fallback_ciphers_disabled.yaml
spec/functions/ssh/add_sshd_config_spec.rb
templates/etc/pam.d/sshd.epp

- Fixed a bug where some changes to sshd configuration did not cause the
sshd service to restart.
- `sshd_config` resources created by `ssh::add_sshd_config()` did not
notify `Service[sshd]`.
- Fixed a bug that caused a compilation error when
`ssh::conf::ensure_sshd_packages` was set to `true`.
- Removed sshd configuration logic pertaining to OpenSSH versions used
in EL6.
- Maintenance
- Adjusted sshd.epp to removed unnecessary empty line in /etc/pam.d/sshd,
when not using oath.
- Reordered a few ssh::add_sshd_config() calls in ssh::conf
(alphabetically), as this makes maintenance of this file easier.
- Removed unnecessary iteration through OS's in the sshd::conf
unit test, because this code does not depend upon OS type/version
facts.
- Expanded unit test coverage for sshd::conf. …

(SIMP-9612) sshd_config resources do not notify sshd service

---

.fixtures.yml
CHANGELOG
metadata.json
spec/spec_helper_acceptance.rb

- Update to augeasproviders_ssh < 5.0.0. Version was bumped to 4.0.0 because
the module dropped support for Augeas < 1.0.0.  This does not affect our modules.
- Make sure all fixture URLs end in '.git', as not all private
GitHub mirrors allow shortened URL
- Configure the acceptance test to fail if rspec reports 0 examples. This
detects some error cases related to bad nodesets.
[SIMP-9281] #comment pupmod-simp-ssh update augeasproviders_ssh
[SIMP-9666] #comment pupmod-simp-ssh acceptance tests configured
[SIMP-9281]: https://simp-project.atlassian.net/browse/SIMP-9281
[SIMP-9666]: https://simp-project.atlassian.net/browse/SIMP-9666

(SIMP-9281) ssh: update augeasproviders_ssh

---

spec/acceptance/nodesets/default.yml
spec/acceptance/suites/compliance/nodesets/default.yml
spec/defines/client/host_config_entry_spec.rb

- update the EL8 nodes in the acceptance tests
to run with generic/centos8 to make sure they using
CentOS 8.4
SIMP-10204 #comment update ssh
SIMP-10245

(SIMP-10204) Ensure testing with CentOS 8.4

---

CHANGELOG
manifests/server/conf.pp
metadata.json
spec/acceptance/suites/default/00_default_spec.rb

The new parameter 'manage_authorizedkeysfile', will be set to true by
default, which means base functionality of the class will not change at
all. If a user flips the variable to false, the authorizedkeysfile
variable will be ignored, allowing users to preserve their existing ssh
key infrastructure.
Fixes #143

(#143) Added parameter to ignore authorizedkeysfile

---

.github/workflows/add_new_issue_to_triage_project.yml
.github/workflows/tag_deploy.yml

* Replace deprecated create-release@v1 
* Convert the remaining ::set-output GHA workflows
The patch enforces a standardized asset baseline using simp/puppetsync,
and may also apply other updates to ensure conformity.

GHA workflow deprecations updates

---

.github/workflows/pr_tests.yml
.puppet-lint.rc
CHANGELOG
Gemfile
manifests/client/host_config_entry.pp
manifests/server/conf.pp
metadata.json
spec/classes/server/conf_spec.rb

This patch adds support for RockyLinux 8
The patch enforces a standardized asset baseline using simp/puppetsync, and may also apply other updates to ensure conformity.

Add RockyLinux 8 support

---

CHANGELOG
lib/puppet/functions/ssh/autokey.rb
metadata.json

Replace calls to `File.exists?` with `File.exist?` for compatibility with Ruby 3
Closes #165

Remove use of File.exists?

---

CHANGELOG
lib/facter/timezone_file.rb
manifests/server.pp
metadata.json
spec/acceptance/suites/default/00_default_spec.rb
spec/classes/server_spec.rb

(#168) Handling a missing /etc/localtime file instead of breaking

---

CHANGELOG
lib/facter/openssh_version.rb
lib/facter/ssh_host_keys.rb
metadata.json

Fixes #174
Tested on windows 11 box:
`C:\Users\vagrant\Custom_facts>facter --custom-dir ./ ssh_host_keys
[
"__PROGRAMDATA__\ssh/ssh_host_rsa_key",
"__PROGRAMDATA__\ssh/ssh_host_ecdsa_key",
"__PROGRAMDATA__\ssh/ssh_host_ed25519_key"
]
C:\Users\vagrant\Custom_facts>facter --custom-dir ./ openssh_version
8.0
`
Tested on rocky8:
`[root@rocky8 custom_facts]# facter --custom-dir ./ openssh_version
8.0
[root@rocky8 custom_facts]# facter --custom-dir ./ ssh_host_keys
[
"/etc/ssh/ssh_host_rsa_key"
]`

quoted ssh command should work on windows and linux
